apiVersion: v1
kind: ServiceAccount
metadata:
  name: grade-submission-api-proxy
  namespace: grade-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grade-submission-api-proxy-role
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grade-submission-proxy-binding
subjects:
  - kind: ServiceAccount
    name: grade-submission-api-proxy
    namespace: grade-demo
roleRef:
  kind: ClusterRole
  name: grade-submission-api-proxy-role
  apiGroup: rbac.authorization.k8s.io

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: grade-submission-proxy-binding
# subjects:
#   - kind: ServiceAccount
#     name: grade-proxy
#     namespace: grade-demo
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io
