apiVersion: v1
kind: Secret
metadata:
  name: grade-sa-token
  namespace: grade-demo
  annotations:
    kubernetes.io/service-account.name: grade-service-account
type: kubernetes.io/service-account-token
